/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zakotwienie;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Jarek
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgWarunkiPrzyczepnosci = new javax.swing.ButtonGroup();
        bgKoniecPreta = new javax.swing.ButtonGroup();
        bgRodzajPreta = new javax.swing.ButtonGroup();
        panelDaneWejsciowe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboBeton = new javax.swing.JComboBox<>();
        cboStal = new javax.swing.JComboBox<>();
        cboFi = new javax.swing.JComboBox<>();
        txtAsreq = new javax.swing.JTextField();
        txtAsprov = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelWarunkiPrzyczepnosci = new javax.swing.JPanel();
        rbtnMierne = new javax.swing.JRadioButton();
        rbtnDobre = new javax.swing.JRadioButton();
        panelKoniecPreta = new javax.swing.JPanel();
        rbtnZagiety = new javax.swing.JRadioButton();
        rbtnProsty = new javax.swing.JRadioButton();
        panelRodzajPreta = new javax.swing.JPanel();
        rbtnSciskany = new javax.swing.JRadioButton();
        rbtnRozciagany = new javax.swing.JRadioButton();
        panelWyniki = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLb = new javax.swing.JTextField();
        txtFbd = new javax.swing.JTextField();
        txtAlfaa = new javax.swing.JTextField();
        txtLbmin = new javax.swing.JTextField();
        txtLbd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOblicz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Długość zakotwienia wg. PN-B-03264:2002 ");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        panelDaneWejsciowe.setBorder(javax.swing.BorderFactory.createTitledBorder("Dane wejściowe"));
        panelDaneWejsciowe.setToolTipText("");
        panelDaneWejsciowe.setName(""); // NOI18N
        panelDaneWejsciowe.setOpaque(false);
        panelDaneWejsciowe.setPreferredSize(new java.awt.Dimension(380, 131));

        jLabel1.setText("Klasa betonu:");

        jLabel2.setText("Klasa stali:");

        jLabel3.setText("Średnica pręta:");

        jLabel5.setText("As,req =");

        jLabel6.setText("As,prov =");

        cboBeton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C12/15 - [B15]", "C16/20 - [B20]", "C20/25 - [B25]", "C25/30 - [B30]", "C30/37 - [B37]", "C35/45 - [B45]", "C40/50 - [B50]", "C45/55 - [B55]", "C50/60 - [B60]" }));
        cboBeton.setPreferredSize(new java.awt.Dimension(100, 20));

        cboStal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-0", "A-I", "A-II", "A-III", "A-IIIN" }));
        cboStal.setPreferredSize(new java.awt.Dimension(60, 20));

        cboFi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "8", "10", "12", "14", "16", "18", "20", "22", "25", "28", "32" }));
        cboFi.setPreferredSize(new java.awt.Dimension(60, 20));

        txtAsreq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAsreq.setText("2.26");
        txtAsreq.setPreferredSize(new java.awt.Dimension(35, 20));

        txtAsprov.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAsprov.setText("2.26");
        txtAsprov.setPreferredSize(new java.awt.Dimension(35, 20));

        jLabel7.setText("[cm2]");

        jLabel8.setText("[cm2]");

        panelWarunkiPrzyczepnosci.setBorder(javax.swing.BorderFactory.createTitledBorder("Warunki przyczepności"));
        panelWarunkiPrzyczepnosci.setPreferredSize(new java.awt.Dimension(170, 35));

        bgWarunkiPrzyczepnosci.add(rbtnMierne);
        rbtnMierne.setText("Mierne");

        bgWarunkiPrzyczepnosci.add(rbtnDobre);
        rbtnDobre.setSelected(true);
        rbtnDobre.setText("Dobre");

        javax.swing.GroupLayout panelWarunkiPrzyczepnosciLayout = new javax.swing.GroupLayout(panelWarunkiPrzyczepnosci);
        panelWarunkiPrzyczepnosci.setLayout(panelWarunkiPrzyczepnosciLayout);
        panelWarunkiPrzyczepnosciLayout.setHorizontalGroup(
            panelWarunkiPrzyczepnosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWarunkiPrzyczepnosciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnDobre)
                .addGap(18, 18, 18)
                .addComponent(rbtnMierne)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelWarunkiPrzyczepnosciLayout.setVerticalGroup(
            panelWarunkiPrzyczepnosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarunkiPrzyczepnosciLayout.createSequentialGroup()
                .addGroup(panelWarunkiPrzyczepnosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMierne)
                    .addComponent(rbtnDobre))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelKoniecPreta.setBorder(javax.swing.BorderFactory.createTitledBorder("Koniec pręta"));
        panelKoniecPreta.setPreferredSize(new java.awt.Dimension(175, 35));

        bgKoniecPreta.add(rbtnZagiety);
        rbtnZagiety.setText("Hak / Pętla");

        bgKoniecPreta.add(rbtnProsty);
        rbtnProsty.setSelected(true);
        rbtnProsty.setText("Prosty");

        javax.swing.GroupLayout panelKoniecPretaLayout = new javax.swing.GroupLayout(panelKoniecPreta);
        panelKoniecPreta.setLayout(panelKoniecPretaLayout);
        panelKoniecPretaLayout.setHorizontalGroup(
            panelKoniecPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKoniecPretaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnProsty)
                .addGap(18, 18, 18)
                .addComponent(rbtnZagiety)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKoniecPretaLayout.setVerticalGroup(
            panelKoniecPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKoniecPretaLayout.createSequentialGroup()
                .addGroup(panelKoniecPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnZagiety)
                    .addComponent(rbtnProsty))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelRodzajPreta.setBorder(javax.swing.BorderFactory.createTitledBorder("Rodzaj pręta"));
        panelRodzajPreta.setPreferredSize(new java.awt.Dimension(175, 35));

        bgRodzajPreta.add(rbtnSciskany);
        rbtnSciskany.setText("Ściskany");

        bgRodzajPreta.add(rbtnRozciagany);
        rbtnRozciagany.setSelected(true);
        rbtnRozciagany.setText("Rozciągany");

        javax.swing.GroupLayout panelRodzajPretaLayout = new javax.swing.GroupLayout(panelRodzajPreta);
        panelRodzajPreta.setLayout(panelRodzajPretaLayout);
        panelRodzajPretaLayout.setHorizontalGroup(
            panelRodzajPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRodzajPretaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnRozciagany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnSciskany)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRodzajPretaLayout.setVerticalGroup(
            panelRodzajPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRodzajPretaLayout.createSequentialGroup()
                .addGroup(panelRodzajPretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnSciskany)
                    .addComponent(rbtnRozciagany))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDaneWejscioweLayout = new javax.swing.GroupLayout(panelDaneWejsciowe);
        panelDaneWejsciowe.setLayout(panelDaneWejscioweLayout);
        panelDaneWejscioweLayout.setHorizontalGroup(
            panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaneWejscioweLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDaneWejscioweLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboBeton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDaneWejscioweLayout.createSequentialGroup()
                        .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboStal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDaneWejscioweLayout.createSequentialGroup()
                                .addComponent(txtAsprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(panelDaneWejscioweLayout.createSequentialGroup()
                                .addComponent(txtAsreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(cboFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKoniecPreta, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(panelRodzajPreta, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(panelWarunkiPrzyczepnosci, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
        );
        panelDaneWejscioweLayout.setVerticalGroup(
            panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaneWejscioweLayout.createSequentialGroup()
                .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboBeton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboStal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAsreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDaneWejscioweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAsprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDaneWejscioweLayout.createSequentialGroup()
                .addComponent(panelWarunkiPrzyczepnosci, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKoniecPreta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRodzajPreta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelWyniki.setBorder(javax.swing.BorderFactory.createTitledBorder("Wyniki"));
        panelWyniki.setPreferredSize(new java.awt.Dimension(278, 91));

        jLabel9.setText("fbd =");

        jLabel10.setText("lb =");

        jLabel11.setText("Alfa a =");

        jLabel12.setText("lbmin =");

        jLabel13.setText("lbd =");

        txtLb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLb.setPreferredSize(new java.awt.Dimension(50, 20));

        txtFbd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFbd.setPreferredSize(new java.awt.Dimension(50, 20));

        txtAlfaa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlfaa.setPreferredSize(new java.awt.Dimension(35, 20));

        txtLbmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLbmin.setPreferredSize(new java.awt.Dimension(50, 20));

        txtLbd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtLbd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLbd.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel17.setText("[mm]");

        jLabel18.setText("[-]");

        jLabel14.setText("[mm]");

        jLabel15.setText("[mm]");

        javax.swing.GroupLayout panelWynikiLayout = new javax.swing.GroupLayout(panelWyniki);
        panelWyniki.setLayout(panelWynikiLayout);
        panelWynikiLayout.setHorizontalGroup(
            panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWynikiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWynikiLayout.createSequentialGroup()
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLbmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addContainerGap())
                    .addGroup(panelWynikiLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtAlfaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelWynikiLayout.setVerticalGroup(
            panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWynikiLayout.createSequentialGroup()
                .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelWynikiLayout.createSequentialGroup()
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelWynikiLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel15)))
                        .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLbmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAlfaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Copyright (c) 2018 by Jarosław Kowalczyk");

        btnOblicz.setText("Oblicz");
        btnOblicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObliczActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelDaneWejsciowe, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelWyniki, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOblicz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDaneWejsciowe, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWyniki, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOblicz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObliczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObliczActionPerformed
 
        String klasaBetonu = cboBeton.getSelectedItem().toString();
        String klasaStali = cboStal.getSelectedItem().toString();
        
        double asReq = Double.parseDouble(txtAsreq.getText());
        double asProv = Double.parseDouble(txtAsprov.getText());
      
        double Fck = 0;
        double Fyd = 0;
        double Fi = Double.parseDouble(cboFi.getSelectedItem().toString());
        
        double gammaC = 1.5;
        double Fbd;
        double fbdZaokr;
        double lb;
        double lbd = 0;
        double lbmin = 0;
        double max = Math.max(10 * Fi, 100);
        double alfaa = 0;
       
        // Przypisanie Fck w zależności od klasy betonu
        switch (klasaBetonu)
        {
            case "C12/15 - [B15]":
                Fck = 12;
                break;
            case "C16/20 - [B20]":
                Fck = 16;
                break;
            case "C20/25 - [B25]":
                Fck = 20;
                break;
            case "C25/30 - [B30]":
                Fck = 25;
                break;
            case "C30/37 - [B37]":
                Fck = 30;
                break;
            case "C35/45 - [B45]":
                Fck = 35;
                break;
            case "C40/50 - [B50]":
                Fck = 40;
                break;
            case "C45/55 - [B55]":
                Fck = 45;
                break;
            case "C50/60 - [B60]":
                Fck = 50;
                break;
            default:
                System.out.println("NIEPRAWIDŁOWE DANE");
                break;
        }
        
        //Przypisanie Fyd w zależności od klasy stali
        switch (klasaStali)
        {
            case "A-0":
                Fyd = 190;
                break;
            case "A-I":
                Fyd = 210;
                break;
            case "A-II":
                Fyd = 310;
                break;
            case "A-III":
                Fyd = 350;
                break;
            case "A-IIIN":
                Fyd = 420;
                break;
            default:
                System.out.println("NIEPRAWIDLOWE DANE");
        }
        
        if (klasaStali.equals("A-0") || klasaStali.equals("A-I")) 
        {
           Fbd = ((0.36 * Math.sqrt(Fck)) / gammaC);
            
           // zaokrąglenie Fbd do 1 miejsca po przecinku (konwersja ze stringa)
           String s = String.valueOf(Fbd);
           fbdZaokr = Double.parseDouble(s);
           fbdZaokr *= 10;
           fbdZaokr = Math.round(fbdZaokr);
           fbdZaokr /= 10;
        } else 
        {  
           double gora = 0.47*(Math.pow((Fck * Fck), 1.0 / 3.0));
           Fbd = (gora/gammaC);
           
           // zaokrąglenie Fbd do 1 miejsca po przecinku (konwersja ze stringa)
           String s = String.valueOf(Fbd);
           fbdZaokr = Double.parseDouble(s);
           fbdZaokr *= 10;
           fbdZaokr = Math.round(fbdZaokr);
           fbdZaokr /= 10;
       }
        
       // Sprawdzenie RadioButtonów Warunki przyczepności
       if (rbtnMierne.isSelected())
       {
           fbdZaokr *= 0.7; 
           
           // zaokrąglenie do 2 miejsca po przecinku (konwersja ze stringa)
           String s = String.valueOf(fbdZaokr);
           fbdZaokr = Double.parseDouble(s);
           fbdZaokr *= 100;
           fbdZaokr = Math.round(fbdZaokr);
           fbdZaokr /= 100;          
       }
       
       // Wyświetlenie wyniku Fbd w textbox
       txtFbd.setText(Double.toString(fbdZaokr));
       
       // Obliczenie lb
       lb = ((Fi / 4) * (Fyd / fbdZaokr));
       
       // Wyświetlenie wyniku lb w textbox
       txtLb.setText(Double.toString(Math.round(lb)));
       
       // Sprawdzenie RadioButtonów Koniec preta
       if (rbtnProsty.isSelected())
       {
           alfaa = 1.0;
       }
       else if (rbtnZagiety.isSelected())
       {
           alfaa = 0.7;
       }
       
       // Wyświetlenie wyniku alfa a w textbox
       txtAlfaa.setText(Double.toString(alfaa));
       
       // Sprawdzenie RadioButtonow Rodzaj pręta
       if (rbtnRozciagany.isSelected())
       {
           lbmin = Math.max((0.3 * lb), max);     
       }
       else if (rbtnSciskany.isSelected())
       {
           lbmin = Math.max((0.6 * lb), max);
       }       
       
       // Obliczenie lbd
       lbd = alfaa * lb * (asReq / asProv);
       
       // Wyświetlenie wyniku lbmin
       txtLbmin.setText(Double.toString(Math.round(lbmin)));
       
       // Wyświetlenie wyniku lbd
       txtLbd.setText(Double.toString(Math.round(lbd)));
       
    }//GEN-LAST:event_btnObliczActionPerformed

    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {   
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgKoniecPreta;
    private javax.swing.ButtonGroup bgRodzajPreta;
    private javax.swing.ButtonGroup bgWarunkiPrzyczepnosci;
    private javax.swing.JButton btnOblicz;
    private javax.swing.JComboBox<String> cboBeton;
    private javax.swing.JComboBox<String> cboFi;
    private javax.swing.JComboBox<String> cboStal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelDaneWejsciowe;
    private javax.swing.JPanel panelKoniecPreta;
    private javax.swing.JPanel panelRodzajPreta;
    private javax.swing.JPanel panelWarunkiPrzyczepnosci;
    private javax.swing.JPanel panelWyniki;
    private javax.swing.JRadioButton rbtnDobre;
    private javax.swing.JRadioButton rbtnMierne;
    private javax.swing.JRadioButton rbtnProsty;
    private javax.swing.JRadioButton rbtnRozciagany;
    private javax.swing.JRadioButton rbtnSciskany;
    private javax.swing.JRadioButton rbtnZagiety;
    private javax.swing.JTextField txtAlfaa;
    private javax.swing.JTextField txtAsprov;
    private javax.swing.JTextField txtAsreq;
    private javax.swing.JTextField txtFbd;
    private javax.swing.JTextField txtLb;
    private javax.swing.JTextField txtLbd;
    private javax.swing.JTextField txtLbmin;
    // End of variables declaration//GEN-END:variables
}
